POST http://localhost:3001/users
Content-Type: application/json

{
    "email":"test3@test.com",
    "password":"strongPass123!"
}

###

GET http://localhost:3001/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGE3ODE1MDg4MjI4MzA4ODNhNjFhODIiLCJpYXQiOjE3NTU4MDgxNzUsImV4cCI6MTc1NTgwODE3OH0.gIlpcZEhk4IqjIT6t3urcm7hgv9zSk60ltSxPthuv-g
