### create reservation
POST http://localhost:3000/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGE1N2JhM2FiYWE4Nzk0YWNlY2RhOWEiLCJpYXQiOjE3NTU2NzU1NjgsImV4cCI6MTc1NjI4MDM2OH0.8Pl2y7PXRy7Pk-9omJ4Os8E2mqH5Qipv8-5bsjhdQE4

{
    "startDate":"08/11/2025",
    "endDate":"10/22/2025",
    "placeId":"123",
    "invoiceId":"12345"
}

### get all reservations
GET http://localhost:3000/reservations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGE1N2JhM2FiYWE4Nzk0YWNlY2RhOWEiLCJpYXQiOjE3NTU2NzU1NjgsImV4cCI6MTc1NjI4MDM2OH0.8Pl2y7PXRy7Pk-9omJ4Os8E2mqH5Qipv8-5bsjhdQE4
### get reservation by id
GET http://localhost:3000/reservations/68999da0f93e993d570b4145

### update reservations by id 
PATCH http://localhost:3000/reservations/68999da0f93e993d570b4145
Content-Type: application/json

{
   "startDate":"08/13/2025" 
}

### delete reservation by id
DELETE http://localhost:3000/reservations/68999da0f93e993d570b4145