### create reservation
POST http://localhost:3000/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGE5YjFjMzE4MzdlYmUyMzMzYjY4NDgiLCJpYXQiOjE3NTU5NTE1NjYsImV4cCI6MTc1NjU1NjM2Nn0.gTmxE0aW8_efoNDc0lSTFkP1pYY3Cu12Uiho9kiZuDg

{
    "startDate":"2025-08-30",
    "endDate":"2025-09-01",
    "placeId":"123",
    "invoiceId":"12345",
    "amount":2
}

### get all reservations
GET http://localhost:3000/reservations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGE5YjFjMzE4MzdlYmUyMzMzYjY4NDgiLCJpYXQiOjE3NTU5NTE1NjYsImV4cCI6MTc1NjU1NjM2Nn0.gTmxE0aW8_efoNDc0lSTFkP1pYY3Cu12Uiho9kiZuDg

### get reservation by id
GET http://localhost:3000/reservations/68a9b794a6a4bf7906f47fee

### check payment status
GET http://localhost:3000/reservations/68a9b794a6a4bf7906f47fee/check-payment-status

### update reservations by id 
PATCH http://localhost:3000/reservations/68a9b024fed1b52fe6e35a4b
Content-Type: application/json

{
   "startDate":"08/13/2025" 
}

### delete reservation by id
DELETE http://localhost:3000/reservations/68999da0f93e993d570b4145